# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Default config for Vagrant

# Don't change this; use vagrantconfig_local.yaml to override these
# settings instead.

# if you need hbase you might want to bump this up to 1024
memory: 256

# enable this to see verbose and debug puppet output
debug_mode: false

# set this to "gui" if vagrant cannot connect
boot_mode: none
