# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
