# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
