#!/bin/bash
#
# socorro-processor    Startup script for the Socorro Processor
#
# chkconfig: 2345 98 01
# description: Socorro Processor service.

# Source function library.
. /etc/rc.d/init.d/functions

progname=`basename $0`

# Source socorro overrides
commonconfig=/etc/socorro/common.conf
config=/etc/socorro/${progname}.conf
if [ -f "$commonconfig" ]; then . $commonconfig; fi
if [ -f "$config" ]; then . $config; fi

script=scripts/startProcessor.py
prefix=/data/socorro
appdir=${prefix}/application
python=/usr/bin/python
pidfile=/var/run/${progname}.pid
lockfile=/var/lock/${progname}.lock
logfile=/var/log/socorro/${progname}.log
user=socorro
RETVAL=0

start() {
        echo -n $"Starting ${progname}: "
        export PYTHONPATH=${appdir}:${prefix}/thirdparty
        /usr/sbin/daemonize -c ${appdir} -a -e ${logfile} -o ${logfile} -p ${pidfile} -u ${user} -l ${lockfile} ${python} ${appdir}/${script}
        RETVAL=$?
        if [ $RETVAL == 0 ]
        then
            echo_success
        else
            echo_failure
        fi
        echo
}

stop() {
	echo -n $"Stopping ${progname}: "
	killproc -p ${pidfile} ${python}
	RETVAL=$?
	echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
        status -p ${pidfile} ${python}
	RETVAL=$?
	;;
  restart)
	stop
	start
	;;
  *)
	echo $"Usage: ${progname} {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
