# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.15 on 2018-09-25 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = []
