# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 1.11.16 on 2018-12-14 19:52

from django.db import connection, migrations


def remove_eventlog_tables(apps, schema_editor):
    cursor = connection.cursor()

    # Drop the pinax-eventlog table because we don't use that app anymore
    cursor.execute("DROP TABLE IF EXISTS eventlog_log")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("crashstats", "0014_auto_20181214_1951")]

    operations = [migrations.RunPython(remove_eventlog_tables, noop)]
