# Generated by Django 2.2.19 on 2021-03-17 22:20

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from django.db import migrations


def delete_data(apps, schema_editor):
    """Delete Fennec productversion data."""
    ProductVersion = apps.get_model("crashstats", "ProductVersion")

    ret = ProductVersion.objects.filter(product_name="Fennec").all().delete()
    print("deleted: %s" % ret[0], end="")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("crashstats", "0021_bug_1657668_product_support"),
    ]

    operations = [migrations.RunPython(delete_data, noop)]
