# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
