# Generated by Django 1.11.16 on 2018-10-12 13:08

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crashstats", "0006_1493768-bug-associations")]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text=b"Name of the platform", max_length=20),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text=b"Short abbreviated name of the platform",
                        max_length=20,
                    ),
                ),
            ],
        )
    ]
