# Generated by Django 2.1.7 on 2019-03-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crashstats", "0016_1523284_fenix")]

    operations = [
        migrations.CreateModel(
            name="MissingProcessedCrashes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crash_id",
                    models.CharField(
                        help_text="crash id for missing processed crash",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="date discovered it was missing"
                    ),
                ),
            ],
        )
    ]
