# Generated by Django 2.1.7 on 2019-04-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashstats', '0019_missing-crashes-migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingProcessedCrashes',
        ),
        migrations.AlterModelOptions(
            name='missingprocessedcrash',
            options={'verbose_name': 'missing processed crash', 'verbose_name_plural': 'missing processed crashes'},
        ),
    ]
