# Generated by Django 2.2.14 on 2020-08-09 23:57

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crashstats", "0020_auto_20190403_2208"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
