# Generated by Django 2.2.14 on 2020-08-09 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crashstats", "0020_auto_20190403_2208"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
