"""Adding ADU by date.

Revision ID: 275826e3abc3
Revises: 523b9e57eba2
Create Date: 2013-10-21 10:41:17.951911

"""

# revision identifiers, used by Alembic.
revision = '275826e3abc3'
down_revision = '523b9e57eba2'

from alembic import op
from socorro.lib import citexttype, jsontype
from socorro.lib.migrations import fix_permissions, load_stored_proc

import sqlalchemy as sa
from sqlalchemy import types
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column




def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'adu_by_build',
    sa.Column(u'adu_by_build_id', sa.INTEGER(), nullable=False),
    sa.Column(u'signature_id', sa.INTEGER(), nullable=False),
    sa.Column(u'adu_date', sa.DATE(), nullable=False),
    sa.Column(u'build_date', sa.DATE(), nullable=False),
    sa.Column(u'buildid', sa.NUMERIC(), server_default='0', nullable=False),
    sa.Column(u'crash_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column(u'adu_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column(u'os_name', citexttype.CitextType(), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], [u'signatures.signature_id'], ),
    sa.PrimaryKeyConstraint(u'adu_by_build_id_id')
    )
    ### end Alembic commands ###
    app_path=os.getcwd()
    procs = [
        'update_adu_by_build.sql'
        , 'backfill_adu_by_build.sql'
    ]
    for myfile in [app_path + '/socorro/external/postgresql/raw_sql/procs/' + line for line in procs]:
        with open(myfile, 'r') as file:
            op.execute(file.read())


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'adu_by_build')
    ### end Alembic commands ###
