"""Fixes bug 1053956 deprecate raw_adu in favor of raw_adi table

Revision ID: 31168908ac42
Revises: e4ea2ae3413
Create Date: 2015-01-27 13:14:38.221177

"""

# revision identifiers, used by Alembic.
revision = '31168908ac42'
down_revision = 'e4ea2ae3413'

from alembic import op
from socorro.lib import citexttype, jsontype, buildtype
from socorro.lib.migrations import fix_permissions, load_stored_proc

import sqlalchemy as sa
from sqlalchemy import types
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_adu')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_adu',
        sa.Column('adu_count', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
        sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('product_os_platform', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('product_os_version', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('product_version', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('build', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('build_channel', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('product_guid', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
        sa.Column('update_channel', sa.TEXT(), autoincrement=False, nullable=True)
    )
    ### end Alembic commands ###
