"""Fixes bug 1149600 remove crontabber_state table

Revision ID: 314f55310264
Revises: 63d05b930c3
Create Date: 2015-03-31 09:10:30.881732

"""

# revision identifiers, used by Alembic.
revision = '314f55310264'
down_revision = '63d05b930c3'

from alembic import op
from socorro.lib import citexttype, jsontype, buildtype
from socorro.lib.migrations import fix_permissions, load_stored_proc

import sqlalchemy as sa
from sqlalchemy import types
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crontabber_state')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crontabber_state',
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('last_updated', name=u'crontabber_state_pkey')
    )
    ### end Alembic commands ###
