"""bug 864391 - create skiplist

Revision ID: 4d86b4efd25d
Revises: e4d30f140ed
Create Date: 2013-05-22 09:16:15.248184

"""

# revision identifiers, used by Alembic.
revision = '4d86b4efd25d'
down_revision = 'e4d30f140ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy.types as types
from sqlalchemy.sql import table, column
from sqlalchemy.dialects import postgresql

def upgrade():
    op.create_table(u'skiplist',
        sa.Column(u'category', sa.TEXT(), nullable=False),
        sa.Column(u'rule', sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint(u'category', u'rule')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'skiplist')
    ### end Alembic commands ###
