"""Crashed per ADU migration.

Revision ID: 52f398dd118e
Revises: 523b9e57eba2
Create Date: 2013-09-26 11:27:26.265531

"""

# revision identifiers, used by Alembic.
revision = '52f398dd118e'
down_revision = '523b9e57eba2'

import os
from alembic import op
from socorro.lib import citexttype, jsontype
from socorro.lib.migrations import fix_permissions, load_stored_proc

import sqlalchemy as sa
from sqlalchemy import types
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'adu_by_build_id',
    sa.Column(u'adu_by_build_id_id', sa.INTEGER(), nullable=False),
    sa.Column(u'signature_id', sa.INTEGER(), nullable=False),
    sa.Column(u'adu_date', sa.DATE(), nullable=False),
    sa.Column(u'build_date', sa.DATE(), nullable=False),
    sa.Column(u'build_id', sa.NUMERIC(), server_default='0', nullable=False),
    sa.Column(u'crash_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column(u'adu_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column(u'os_name', sa.citext, nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], [u'signatures.signature_id'], ),
    sa.PrimaryKeyConstraint(u'adu_by_build_id_id')
    )
    ### end Alembic commands ###
    app_path=os.getcwd()
    procs = [
        'update_adu_by_build.sql'
        , 'backfill_adu_by_build.sql.sql'
    ]
    for myfile in [app_path + '/socorro/external/postgresql/raw_sql/procs/' + line for line in procs]:
        with open(myfile, 'r') as file:
            op.execute(file.read())

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'adu_by_build_id')
    ### end Alembic commands ###
