"""Adding uuid to extensions

Revision ID: e5eb3c07f2a
Revises: 5316d4cfc03a
Create Date: 2013-03-26 14:24:56.425147

"""

# revision identifiers, used by Alembic.
revision = 'e5eb3c07f2a'
down_revision = '5316d4cfc03a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'extensions', sa.Column(u'uuid', postgresql.UUID(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'extensions', u'uuid')
    ### end Alembic commands ###
