# Derived from the webapp so that crontabber has access to the webapp's
# node dependencies.
FROM local/socorro_webapp

USER root

COPY ./crontabber/package.json /crontabber-deps/package.json
COPY ./crontabber/package-lock.json /crontabber-deps/package-lock.json
RUN cd /crontabber-deps/ && npm install

ENV CONTAINERNAME crontabber

USER app

CMD ["/app/docker/run_crontabber.sh"]
