FROM python:3.10.5-alpine3.16@sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1

ARG groupid=5000
ARG userid=5000

WORKDIR /app/

RUN addgroup -g $groupid app && \
    adduser --disabled-password --gecos "" --home /home/app --ingroup app --uid $userid app && \
    chown app:app /app/

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN pip install -U 'pip>=20' && \
    pip install --no-cache-dir 'kent==0.5.0'

USER app

ENTRYPOINT ["/usr/local/bin/kent-server"]
CMD ["run"]
