# Derived from the webapp so that crontabber has access to the webapp's
# node dependencies.
FROM local/socorro_webapp

USER root

COPY ./docker/set_up_sentry_cli.sh /tmp/
RUN /tmp/set_up_sentry_cli.sh

ENV CONTAINERNAME crontabber

USER app

CMD ["/app/docker/run_crontabber.sh"]
