FROM local/socorro_base

# This uses a .ini file for behavior configuration and environment variables for
# environment and secret configuration.

ENTRYPOINT ["/usr/local/bin/socorro", "processor"]
CMD ["--admin.conf" "/app/docker/config/processor.ini]
