/** Desired capabilities */
def capabilities = [
  browserName: 'Firefox',
  version: '56.0',
  platform: 'Windows 10'
]

pipeline {
  agent any
  libraries {
    lib('fxtest@1.9')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 1, unit: 'HOURS')
  }
  environment {
    PYTEST_ADDOPTS =
    "-n=10 " +
    "--tb=short " +
    "--color=yes " +
    "--driver=SauceLabs " +
    "--variables=capabilities.json"
    PULSE = credentials('PULSE')
    SAUCELABS = credentials('SAUCELABS')
  }
  stages {
    stage('Lint') {
      steps {
        sh "tox -c e2e-tests/tox.ini -e flake8"
      }
    }
    stage('Test') {
      steps {
        writeCapabilities(capabilities, 'e2e-tests/capabilities.json')
        sh "tox -c e2e-tests/tox.ini -e py27"
      }
      post {
        always {
          archiveArtifacts 'e2e-tests/results/*'
          junit 'e2e-tests/results/*.xml'
          submitToActiveData('e2e-tests/results/py27_raw.txt')
          submitToTreeherder('socorro', 'e2e', 'End-to-end integration tests', 'e2e-tests/results/*', 'e2e-tests/results/py27_tbpl.txt')
          publishHTML(target: [
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportDir: 'e2e-tests/results',
            reportFiles: "py27.html",
            reportName: 'HTML Report'])
        }
      }
    }
  }
  post {
    failure {
      emailext(
        attachLog: true,
        attachmentsPattern: 'e2e-tests/results/py27.html',
        body: '$BUILD_URL\n\n$FAILED_TESTS',
        replyTo: '$DEFAULT_REPLYTO',
        subject: '$DEFAULT_SUBJECT',
        to: '$DEFAULT_RECIPIENTS')
    }
    changed {
      ircNotification('#breakpad')
      ircNotification('#fx-test-alerts')
    }
  }
}
