\set ON_ERROR_STOP 1

DROP TABLE IF EXISTS alexa_topsites CASCADE;
DROP TABLE IF EXISTS top_crashes_by_signature CASCADE;
DROP TABLE IF EXISTS top_crashes_by_url CASCADE;
DROP TABLE IF EXISTS top_crashes_by_url_signature CASCADE;
DROP TABLE IF EXISTS signature_build CASCADE;
DROP TABLE IF EXISTS signature_first CASCADE;
DROP TABLE IF EXISTS signature_bugs_rollup CASCADE;
DROP TABLE IF EXISTS signature_productdims CASCADE;
DROP TABLE IF EXISTS release_build_type_map CASCADE;
DROP TABLE IF EXISTS builds CASCADE;
DROP TABLE IF EXISTS osdims CASCADE;
DROP TABLE IF EXISTS productdims_version_sort CASCADE;
DROP TABLE IF EXISTS product_visibility CASCADE;
DROP TABLE IF EXISTS productdims CASCADE;
DROP TABLE IF EXISTS urldims CASCADE;
