# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolsupload',
            name='user',
        ),
        migrations.DeleteModel(
            name='SymbolsUpload',
        ),
    ]
