from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to
from . import views


urlpatterns = patterns('',
    url(r'^products/(?P<product>\w+)$', views.products,
        name='crashstats.products'),
    url(r'^products/(?P<product>\w+)/versions/(?P<versions>[\w\.()]+)$',
        views.products,
        name='crashstats.products'),
    url(r'^topcrasher/byversion/(?P<product>\w+)/(?P<version>[\w\.()]+)$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url(r'^topcrasher/byversion/(?P<product>\w+)/(?P<version>[\w\.()]+)/(?P<days>\d+)$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url(r'^topcrasher/byversion/(?P<product>\w+)/(?P<version>[\w\.()]+)/(?P<days>\d+)/(?P<crash_type>\w+)$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url(r'^topcrasher/byos/(?P<product>\w+)/(?P<version>[\w\.()]+)/(?P<os_name>[\w\s]+)/(?P<days>\d+)/(?P<crash_type>\w+)$',
        views.topcrasher,
        name='crashstats.topcrasher'),
    url(r'^daily$', views.daily,
        name='crashstats.daily'),
    url(r'^products/(?P<product>\w+)/builds$', views.builds,
        name='crashstats.builds'),
    url(r'^hangreport/byversion/(?P<product>\w+)/$', views.hangreport,
        name='crashstats.hangreport'),
    url(r'^hangreport/byversion/(?P<product>\w+)/(?P<version>[\w\.()]+)$',
        views.hangreport,
        name='crashstats.hangreport'),
    url(r'^products/(?P<product>\w+)/topchangers$', views.topchangers,
        name='crashstats.topchangers'),
    url(r'^products/(?P<product>\w+)/versions/(?P<versions>[\w\.()]+)/topchangers$',
        views.topchangers,
        name='crashstats.topchangers'),
    url(r'^report/list$', views.report_list,
        name='crashstats.report_list'),
    url(r'^report/index/(?P<crash_id>.*)$', views.report_index,
        name='crashstats.report_index'),
    url(r'^query$', views.query,
        name='crashstats.query'),
    url(r'^correlation/bulk_ajax/(?P<correlation_type>\w+)/(?P<product>\w+)/(?P<version>[\w\.()]+)/$', views.correlation,
        name='crashstats.correlation'),
    url(r'^buginfo/bug', views.buginfo,
        name='crashstats.buginfo'),
    url(r'^$', redirect_to, {'url': '/products/Firefox'}),
)
