#!/bin/bash
# test specific setup and execution

# copy default unit test configs
pushd socorro/unittest/config
for file in *.py.dist
do
configp $file `basename $file .dist`
done
popd

errors=0
while read d
do
    if [ ! -f "$d/__init__.py" ]
    then
        echo "$d is missing an __init__.py file, tests will not run"
        errors=$((errors+1))
    fi
done < <(find socorro/unittest/* -not -name logs -type d)

if [ $errors != 0 ]
then
    exit 1
fi

# iff on jenkins
if [ $JENKINS_HOME ]
then
    # Override hostnames for jenkins
    export DB_HOST="jenkins-pg92"
    export RABBITMQ_HOST="rabbitmq-zlb.webapp.phx1.mozilla.com"
    export RABBITMQ_USERNAME="socorro-jenkins"
    export RABBITMQ_PASSWORD="aPassword"
    export RABBITMQ_VHOST="socorro-jenkins"
    export ES_HOST="jenkins-es20"
    export ES_URLS="http://jenkins-es20:9200"

    # RHEL postgres 9 RPM installs pg_config here, psycopg2 needs it
    export PATH=/usr/pgsql-9.2/bin:$PATH
    echo "My path is $PATH"
fi

# run unit tests
make test database_username=test database_hostname=$DB_HOST database_password=aPassword database_port=5432 database_superusername=test database_superuserpassword=aPassword elasticSearchHostname=$ES_HOST elasticsearch_urls=$ES_URLS

# run socorro integration test
echo "Running integration test..."
./scripts/rabbitmq-integration-test.sh --destroy
./scripts/elasticsearch-integration-test.sh
