# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific aliases and functions
VENV="${HOME}/socorro/socorro-virtualenv/bin/activate"
if [ -f $VENV ] && [ -r $VENV ]; then
    . $VENV
    export PYTHONPATH=.
fi

# Add pg directory to path so pg-config works
export PATH=$PATH:/usr/pgsql-9.4/bin/
