# Generated by Django 2.2 on 2019-04-30 12:42

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cron", "0004_auto_20181214_1951")]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="app_name",
            field=models.CharField(
                help_text="the Django command", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="app_name",
            field=models.CharField(
                help_text="the Django command this log entry is for", max_length=100
            ),
        ),
    ]
