# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180522_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20),
        ),
    ]
