# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:524.0.0-emulators@sha256:11e9b10b6d61177b0046fcb5f1e9479f567a5dacbf66d194baf5a8872653c857
# also available as google/cloud-sdk:<version>-emulators
