# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:525.0.0-emulators@sha256:8f567aab0e9cc5f5dd79c2d81122dfe0ddb8e8ed91932a702a48e849d387f2c1
# also available as google/cloud-sdk:<version>-emulators
