# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:510.0.0-emulators@sha256:63160bca67cc4ab8382a7bfa51ec7901c85944bd9354ab46d5234101a2f1af9d
# also available as google/cloud-sdk:<version>-emulators
